en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-opaque-tokens.md
The API Name can have spaces when creating through the dev-first approach. In subscription validation, this becomes a problem because, in API Manager, the API Name cannot have spaces.
This PR adds a note by mentioning this behaviour in the docs.
Fixes https://github.com/wso2/product-microgateway/issues/616
> Brief description of the new feature or bug fix as it will …
=> Add note to opaque token subscription validation scenario.

en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md, en/docs/how-tos/security/api-authorization/subscription-validation.md, en/docs/reference/commandline-options/toolkit-commands.md, en/mkdocs.yml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
Resolves issue https://github.com/wso2/product-microgateway/issues/1204, https://github.com/wso2/product-microgateway/issues/846
> Brief description of the new feature or bug fix as it will appear in the release …
=> Add docs for toolkit commands and subscription validation

en/docs/getting-started/quick-start-guide/quick-start-guide-binary.md, en/docs/getting-started/quick-start-guide/quick-start-guide-docker.md
> Both docker and vm QSGs were having formatting and invalid content issues. Those were fix.
=> Fix QSG issues

en/theme/material/base.html
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> adding algolia search key

en/theme/material/base.html
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> fixed sytanx issue

en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md, en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-opaque-tokens.md, en/docs/how-tos/security/api-authorization/subscription-validation.md
* Update JWT token validation docs
* Update Opaque token validation docs.
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
Fixes https://github.com/wso2/docs-mg/issues/27
> …
=> Fix API authentication and subscription validation docs.

en/docs/how-tos/support-custom-claims-mapping.md, en/mkdocs.yml
Add documentation for support custom claim mapping feature
=> add documentation for support custom claim mapping feature

en/docs/how-tos/overriding-endpoint-information/overriding-endpoints-for-developer-first-approach-apis.md
As $subejcet, this will modify the way to override endpoints for basic auth protected endpoints at runtime and add the way  to overriding endpoints for non-basic auth protected endpoints
fixes #12 
fixes #12 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for …
=> Make corrections for Overriding Endpoints at runtime (Developer-first Approach APIs)

en/docs/how-tos/security/api-authentication/mutual-ssl-authentication.md
> add doc for mutual-ssl authentication validation per API level
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> add doc for mutual-ssl authentication validation per API level

en/docs/how-tos/service-discovery.md
> Update curl commands to etcdctl commands as using etcdctl tool is much easier than using curl commands.
Fixes wso2/product-microgateway#1355
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
=> Update curl commands to etcdctl commands in the Service Discovery page.

en/docs/reference/configurations/micro-gw.conf.md, en/docs/reference/configurations/toolkit-config.toml.md
This PR updates the documentation pages related to configuration.
* micro-gw.conf page (https://mg.docs.wso2.com/en/latest/reference/configurations/micro-gw.conf/)
* toolkit-config.toml page (https://mg.docs.wso2.com/en/latest/reference/configurations/toolkit-config.toml/)
Fixes #
---
=> Update the Microgateway and Toolkit config docs

en/docs/how-tos/rate-limiting/distributed-throttling.md
Add "how to" documentation for Distributed Throttling.
Fixes #
---
=> Update the distributed throttling page to use binary publisher

en/docs/concepts/event-hub-and-subscription-validation.md, en/mkdocs.yml
This PR adds the event hub and the subscription validation concepts documentation.
Fixes #
---
=> Add Event hub and subscription validation concepts doc

en/docs/install-and-setup/configuration-for-wso2-api-manager.md, en/docs/install-and-setup/migrating-from-previous-versions.md, en/mkdocs.yml
* Add migration from previous versions page
* Fix Configuration with API manager page
Fixes #38
---
=> Add Migration docs

en/docs/how-tos/passing-enduser-attributes-to-the-backend-using-jwt.md
Provide documentation for user claim retrieval from a remote endpoint.
Fixes https://github.com/wso2/product-microgateway/issues/1196
---
=> Update the docs with claim retrieval implementation

en/docs/how-tos/observability.md, en/docs/reference/configurations/deployment.toml-for-docker.md, en/docs/reference/configurations/deployment.toml-for-kubernetes.md, en/docs/reference/default-ports.md, en/docs/reference/project-directory.md, en/docs/troubleshooting/adding-debug-logs.md, en/docs/troubleshooting/troubleshooting.md
Fix formatting issues.
Fixes #55 
---
=> Fix formatting issues

en/docs/how-tos/analytics-for-microgateway.md
Fixed broken images
fix issue #16 
---
=> Fix broken images in analytics doc

en/docs/faqs.md
Reviewed FAQ doc.
Fixes #20
---
=> Fix FAQ documentation

en/docs/how-tos/endpoints/overriding-endpoint-information/overriding-endpoints-for-imported-apis.md, en/docs/reference/configurations/deployment.toml-for-docker.md, en/docs/reference/configurations/deployment.toml-for-kubernetes.md
Fix formatting.
Fix repeated cluttered content
Add sample values for docker and k8 configs
Fixes #51
---
=> Format overriding endpoints doc

en/docs/concepts/event-hub-and-subscription-validation.md, en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md, en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-opaque-tokens.md, en/docs/install-and-setup/configuration-for-wso2-api-manager.md, en/docs/reference/commandline-options/toolkit-commands.md
This PR fixes the broken documentation links.
Fixes #
---
=> Fix broken documentation links

en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md
Describes the audience claim in the jwt validation
Fixes #
---
=> Fix audince claim description

en/docs/getting-started/quick-start-guide/quick-start-guide-binary.md, en/docs/getting-started/quick-start-guide/quick-start-guide-docker.md, en/docs/includes/invoke-api-with-api-key.md
This PR updates the QSG to use petstore version 3 open API file
Fixes #
---
=> Update QSG to petstore v3

en/docs/how-tos/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md, en/docs/how-tos/support-custom-claims-mapping.md
Fixes https://github.com/wso2/docs-mg/issues/99
Fixes https://github.com/wso2/docs-mg/issues/103
=> Restructure custom claims mapping doc and Add sub claim details to JWT doc

en/docs/concepts/event-hub-and-subscription-validation.md, en/docs/how-tos/security/api-authorization/api-authorization.md, en/docs/how-tos/security/api-authorization/subscription-validation.md
=> Restructure subscription validation doc

en/docs/how-tos/endpoints/defining-a-backend-security-scheme.md, en/docs/how-tos/endpoints/overriding-endpoint-information/overriding-endpoints-for-developer-first-approach-apis.md, en/docs/how-tos/service-discovery.md, en/docs/install-and-setup/install-on-docker.md, en/docs/troubleshooting/adding-debug-logs.md, en/mkdocs.yml
=> Add docker commands

en/docs/concepts/rate-limiting.md, en/docs/how-tos/rate-limiting/adding-throttling-policies.md, en/docs/how-tos/rate-limiting/distributed-throttling.md, en/mkdocs.yml
This PR will add some corrections to the local rate limiting documentation.
Fixes https://github.com/wso2/docs-mg/issues/94 
Fixes https://github.com/wso2/docs-mg/issues/78
---
=> Update rate limiting documentation.

en/docs/how-tos/endpoints/connect-to-an-endpoint-via-a-proxy.md, en/mkdocs.yml
Add proxy related config documentation.
Fixes #101 
---
=> Fix #101 - Add proxy server docs

en/docs/install-and-setup/health-check-endpoints.md, en/docs/reference/default-ports.md, en/mkdocs.yml
This PR will move the `health check endpoints` topic to the `Install and Setup` section
Fixes https://github.com/wso2/docs-mg/issues/90
---
=> Move "health check endpoints" topic to a new location.

en/docs/how-tos/endpoints/overriding-endpoint-information/overriding-endpoints-for-developer-first-approach-apis.md, en/docs/how-tos/endpoints/overriding-endpoint-information/overriding-endpoints-for-imported-apis.md
Fixes issue regarding the overriding endpoint details
Fixes #85 
---
=> Fix #85 - Override endpoint details

en/docs/troubleshooting/troubleshooting.md
This PR adds updated error codes to troubleshooting documentation.
Fixes https://github.com/wso2/docs-mg/issues/66
=> Add updated error codes to troubleshooting documentation

en/docs/how-tos/http-2.0.md
Improve http2 docs with new configurations
Fixes #81 
---
=> Fix #81 - Improve http2 docs

en/docs/concepts/openapi-extensions.md
This PR will add corrections to `x-auth-type` extention.
Fixes https://github.com/wso2/docs-mg/issues/98
---
=> Add corrections to "x-auth-type" extention.

en/docs/how-tos/analytics-for-microgateway.md
Correcting `task.uploadFiles = true` property in [1] page as  `taskUploadFiles = true` as it stated in the page [2].
Correcting the formatting and alignment issues on page [3].
[1]. https://mg.docs.wso2.com/en/latest/how-tos/analytics-for-microgateway/
[2]. https://mg.docs.wso2.com/en/latest/reference/configurations/micro-gw.conf/
[3]. https://mg.docs.wso2.com/en/latest/how-tos/analytics-for-microgateway/#step-2-configuring-the-microgateway-for-analytics
Fixes #
---
=> [Master] Change task.uploadFiles property and fix formatting issues

en/docs/how-tos/analytics-for-microgateway.md
Correcting `task.uploadFiles = true` property in [1] page as  `taskUploadFiles = true` as it stated in the page [2].
Correcting the formatting and alignment issues on page [3].
[1]. https://mg.docs.wso2.com/en/latest/how-tos/analytics-for-microgateway/
[2]. https://mg.docs.wso2.com/en/latest/reference/configurations/micro-gw.conf/
[3]. https://mg.docs.wso2.com/en/latest/how-tos/analytics-for-microgateway/#step-2-configuring-the-microgateway-for-analytics
Fixes #
---
=> [3.2.0] Change task.uploadFiles property and fix formatting issues

en/docs/how-tos/preserve-override-headers.md, en/mkdocs.yml
This PR adds preserve/override headers documentation.
Fixes https://github.com/wso2/docs-mg/issues/152
=> Add preserve/override headers doc

en/docs/how-tos/rate-limiting/distributed-throttling.md
This PR updates the Distributed Throttling documentation
Fixes https://github.com/wso2/docs-mg/issues/91
=> Update Distributed Throttling documentation

en/docs/how-tos/security/rejecting-revoked-tokens.md
=> Review token revocation doc

en/docs/how-tos/security/api-authentication/mutual-ssl-authentication.md
This PR adds mutual SSL protected backends documentation.
Fixes https://github.com/wso2/docs-mg/issues/87
=> Add mutual SSL protected backends documentation

en/docs/how-tos/security/transport-security.md, en/docs/reference/configurations/micro-gw.conf.md
Add backend mutual SSL documentation and configuration reference.
Fixes #
---
=> Add backend mtls documentation

en/docs/how-tos/message-transformation/message-transformation-overview.md, en/docs/how-tos/message-transformation/write-ballerina-interceptors.md, en/docs/how-tos/message-transformation/write-java-interceptors.md, en/mkdocs.yml
Moved the ballerina and java interceptors in tow two separate pages
Fixes #72 
---
=> Fix #72 - Refactor message transformation page

en/docs/how-tos/endpoints/defining-a-backend-security-scheme.md, en/docs/how-tos/endpoints/defining-endpoints-in-an-openapi-definition.md
=> Restructure endpoint doc

en/mkdocs.yml
=> Add doc to ToC

en/docs/install-and-setup/install-on-docker.md, en/docs/troubleshooting/adding-debug-logs.md
Fixes commands with setting conf values as docker environment variables.
Fixes #
---
=> Fix docker env var

en/docs/how-tos/security/api-authentication/mutual-ssl-authentication.md
=> Incorrect configurations provided in MG Mutual SSL Authetication Doc

en/docs/install-and-setup/migrating-from-previous-versions.md, en/docs/reference/configurations/configurations-overview.md, en/docs/reference/configurations/configuring-micro-gw-conf-for-docker.md, en/docs/reference/configurations/configuring-micro-gw-conf-for-kubernetes.md, en/docs/reference/configurations/micro-gw-conf-config-catalog.md, en/mkdocs.yml
- fixes https://github.com/wso2/product-microgateway/issues/2671
- fixes https://github.com/wso2/docs-apim/issues/5476
**configurations-overview.md**
**configuring-micro-gw-conf-for-docker.md**
**configuring-micro-gw-conf-for-kubernetes.md**
=> fixes https://github.com/wso2/product-microgateway/issues/2671

en/docs/assets/css/theme.css, en/theme/material/partials/header.html
=> Mention about CC release in mg docs page

en/theme/material/partials/header.html
=> Fix for broken url

en/docs/how-tos/endpoints/connect-to-an-endpoint-via-a-proxy.md
Fix a typo in proxy enable tag
Fixes #
---
=> update the typo in [httpClients.proxy] tag enable

en/docs/how-tos/observability.md
Fixes
- https://github.com/wso2/product-microgateway/issues/2204
Page : https://mg.docs.wso2.com/en/latest/how-tos/observability/
=> Fix indentation in prometheus.yaml

en/docs/getting-started/quick-start-guide/quick-start-guide-docker.md, en/docs/includes/obtain-api-key.md
=> Fix get token query

en/docs/how-tos/adding-apis/using-an-openapi-definition.md
=> Add whitelist URLs when building petstore project

en/docs/how-tos/message-transformation/write-ballerina-interceptors.md
=> Correct link for ballerina API docs

en/docs/how-tos/security/transport-security.md
This PR adds the notes for TLSv1.3 support in API Microgateway.
Fixes https://github.com/wso2/docs-apim/issues/9222
=> Add note for TLSv1.3 support

en/docs/faqs.md
This PR adds the Java version compatibility with API Microgateway 3.2.0.
=> Add Java version compatibility docs
